Repository rebuy-de/aws-nuke, pull requests merged in 2018-06, with the labels that each got.

#193 fix SagemakerNotebookInstance not deleted
  resources/sagemaker-notebookinstances.go
Labels: kind/bug

#195 Parallelise scan API requests
  cmd/scan.go
  cmd/scan_test.go
  glide.lock
  glide.yaml
Labels: kind/enhancement

#198 add advanced filters via properties
  README.md
  cmd/log.go
  cmd/nuke.go
  cmd/queue.go
  config/example.yaml
  pkg/config/filter.go
  resources/ec2-vpc.go
  resources/iam-role-policy-attachments.go
  resources/iam-user-access-keys.go
  resources/iam-user-policy-attachments.go
  resources/interface.go
  resources/route53-hosted-zones.go
  resources/route53-resource-records.go
  resources/s3-multipart-uploads.go
  resources/s3-objects.go
Labels: kind/enhancement

#205 bump AWS SDK v1.14.9
  glide.lock
  glide.yaml
Labels: kind/other

#206 only warn on missing services for regions
  cmd/scan.go
  pkg/awsutil/errors.go
  pkg/awsutil/session.go
Labels: kind/enhancement

#204 strict config parsing
  cmd/root.go
  glide.lock
  glide.yaml
  pkg/config/config.go
Labels: kind/enhancement

#167 Add AppStream 2.0 Service Coverage
  resources/appstream-directoryconfigs.go
  resources/appstream-fleets.go
  resources/appstream-fleetstates.go
  resources/appstream-imagebuilders.go
  resources/appstream-imagebuilderwaiters.go
  resources/appstream-images.go
  resources/appstream-stack-fleet-attachments.go
  resources/appstream-stacks.go
Labels: kind/resource
