Repository rebuy-de/aws-nuke, pull requests merged in 2018-08, with the labels that each got.

#253 fix nil dereference
  cmd/nuke.go
  pkg/awsutil/account.go
  pkg/awsutil/session.go
Labels: kind/bug

#251 Strip debug info using ldflags on build
  golang.mk
Labels: kind/enhancement

#255 nuke EC2 NetworkInterfaces
  resources/ec2-network-interfaces.go
Labels: kind/resource
